### ISSUE TITLE
GNU R + Arch Linux + Geospatial

### ISSUE THREAD

**Issue by ismailsunni** [ismailsunni/dockeRs#15]

**Comment by ismailsunni** [comment]
Not able to install system dependency that does not exist in the official Arch repository. Must install from AUR (e.g. https://aur.archlinux.org/packages/bwidget/)

**Comment by ismailsunni** [comment]
Other packages that do not exist in the official repo but exist in AUR:
- bwidget
- jags
- saga-gis
- swftools
- v8

**Comment by nuest** [comment]
AUR = Arch User Repository
