### ISSUE TITLE
`ctv` is Installed, but Not Working

### ISSUE THREAD

**Issue by ismailsunni** [ismailsunni/dockeRs#35]
I can install `ctv` package, but I can't use it. See more here https://github.com/bedatadriven/renjin/issues/490

**Comment by nuest** [comment]
Can you clarify for which platform / R implementation this issue exists?

**Comment by ismailsunni** [comment]
Renjin on Debian. I think it's answered by this comment https://github.com/bedatadriven/renjin/issues/490#issuecomment-553485783
